# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BeLBCxRgbUnmjyanKCx8UDF2oobCkzQW
"""

import pandas as pd
import numpy as np
df= pd.read_csv('/content/retail_store_sales.csv')
df.head(10)
df.info()
df.describe()
print("\nDtypes:")
print(df.dtypes)
print("\nMissing values per column:")
print(df.isnull().sum())

df.columns = [c.strip().replace(" ", "_").lower() for c in df.columns]

drop_mask = df['transaction_date'].isnull() & df.get('item', pd.Series()).isnull()
df.drop(df[drop_mask].index, inplace=True)

df.isnull().sum()
df['total_spent'].isnull().sum()
df['total_spent'].fillna(df['total_spent'].mean(), inplace=True)
df['total_spent'].isnull().sum()
df['total_spent'].describe()

df['total_spent'].plot(kind='hist', bins=50, title='Total Spent Distribution')
import matplotlib.pyplot as plt
plt.show()

plt.figure(figsize=(10,5))
df.groupby('transaction_date')['total_spent'].sum().plot(kind='line', marker='o')
plt.title("Total Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.grid(True)
plt.show()

categorical_cols = ['category', 'payment_method', 'location', 'discount_applied']

for col in categorical_cols:
    plt.figure(figsize=(8,4))
    df[col].value_counts().plot(kind='bar', color='skyblue', edgecolor='black')
    plt.title(f"{col} - Count of Records")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.show()

most_sold = df.groupby('item')['quantity'].sum().sort_values(ascending=False)
print(most_sold.head(10))
most_sold.head(10).plot(kind='bar', color='skyblue', edgecolor='black', figsize=(8,5))
plt.title("Top 10 Most Sold Products (by Quantity)")
plt.ylabel("Total Quantity Sold")
plt.xlabel("Product")
plt.xticks(rotation=45)
plt.show()